services:
  web-api:
    image: uniletters.webapi
    build:
      context: .
      dockerfile: UniLetters.WebApi/Dockerfile
    ports:
      - "9877:8080"

  database:
    image: postgres
    ports:
      - "9878:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: uni!
    volumes:
      - uniletters_data:/var/lib/postgresql/data

volumes:
  uniletters_data: